### ISSUE TITLE
Sine example program creates garbage noise every other start

### ISSUE THREAD

**Issue by stefan-reich** [jaudiolibs/examples#1]
Hi,

EVERYTHING IS SO WEIRD IN JAVASOUND LAND.

It might not even be your fault.

Either way, I ported your Sine example program to my language JavaX: [http://tinybrain.de/1009655](http://tinybrain.de/1009655)

It is literally the same program as yours, just repackaged.

When I start it, sometimes I get the sine wave - and sometimes just noise. Like a 50% chance per program start.

This is on Peppermint Linux 7 64 bit, Oracle JDK 8, PulseAudio.

Any ideas?

Thanks

**Comment by neilcsmith-net** [comment]
Hi,

I assume the none-ported example behaves the same?

Things to try -

- Increase the buffer size - 512, 1024, 2048.  The example value is possibly a bit low and might be pushing it on some systems.  Praxis LIVE defaults to 2048.
- Try changing the sample rate to 48,000.  Sometimes devices are opened at 48,000 and resampling from 44,100 causes issues.  Praxis LIVE is defaulting to 48,000.
- Try passing JSTimingMode.BLOCKING in the AudioConfiguration - add it after the Connections.OUTPUT.
- Why Oracle JDK?  OpenJDK has a proper PulseAudio Mixer which will usually be the default and works better in my experience than the Alsa Mixer through PulseAudio.  Also look at the DeviceIteration example  - you can try passing in another Device in the AudioConfiguration (again after Connections.OUTPUT).

Best wishes, Neil

**Comment by neilcsmith-net** [comment]
Any further on this?  If not, I'll close this issue.

Thanks, Neil
